language: php

sudo: required

branches:
  only:
      - master

cache:
   directories:
       - $HOME/.composer/cache

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1

matrix:
    fast_finish: true
    allow_failures:
        - php: 7.1

before_install:
    - sudo add-apt-repository -y ppa:moti-p/cc
    - sudo apt-get update
    - sudo apt-get -y --reinstall install imagemagick
    - sudo apt-get -y --reinstall install libmagickwand4
    - composer self-update

install:
    - composer install
    - composer require --dev satooshi/php-coveralls:~0.6

script:
    - mkdir -p build/logs
    - phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_success:
    - travis_retry php vendor/bin/coveralls -v

notifications:
    email: pierstoval@gmail.com
