language: php

sudo: required

branches:
  only:
      - master

cache:
   directories:
       - $HOME/.composer/cache

matrix:
    fast_finish: true
    include:
        - php: 7.1
          env: 'IM_VERSION="ImageMagick6"'
        - php: 7.1
          env: 'IM_VERSION="ImageMagick"' # IM 7
        - php: 7.2
          env: 'IM_VERSION="ImageMagick6"'
        - php: 7.2
          env: 'IM_VERSION="ImageMagick"' # IM 7

before_install:
    - composer self-update
    - export TAR_URL=$(curl -L https://api.github.com/repos/ImageMagick/$IM_VERSION/tags | jq .[1].tarball_url | tr -d '"')
    - curl -L $TAR_URL | tar xz
    - cd ImageMagick-$IM_VERSION*
    - ./configure
    - make
    - sudo make install

install:
    - cd ..
    - composer install --no-interaction
    - composer require --dev satooshi/php-coveralls:~0.6

script:
    - mkdir -p build/logs
    - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_success:
    - travis_retry php vendor/bin/coveralls -v

notifications:
    email: pierstoval@gmail.com
