language: php

sudo: required

branches:
  only:
      - master

cache:
   directories:
       - $HOME/.composer/cache

php:
    - 7.1
    - 7.2

matrix:
    fast_finish: true
    allow_failures:
        - php: 7.2

before_install:
    - composer self-update

install:
    - composer install
    - composer require --dev satooshi/php-coveralls:~0.6

script:
    - mkdir -p build/logs
    - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_success:
    - travis_retry php vendor/bin/coveralls -v

notifications:
    email: pierstoval@gmail.com
