language: php

sudo: required

branches:
  only:
      - master

cache:
   directories:
       - $HOME/.composer/cache

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7
    - hhvm

matrix:
    fast_finish: true
    allow_failures:
        - php: 7
        - php: hhvm

before_install:
    - sudo add-apt-repository -y ppa:moti-p/cc
    - sudo apt-get update
    - sudo apt-get -y --reinstall install imagemagick
    - if [ "$TRAVIS_PHP_VERSION" = "hhvm" ]; then sudo apt-get -y --reinstall install libmagickwand4; fi;
    - composer self-update

install:
    - composer install
    - composer require --dev satooshi/php-coveralls:~0.6

script:
    - mkdir -p build/logs
    - phpunit --coverage-clover build/logs/clover.xml

after_success: |
    if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v --config .coveralls.yml; fi;

notifications:
    email: pierstoval@gmail.com
